from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch

from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    PageBreak,
)


def generate_interview_report(
    readiness_score,
    readiness_status,
    eye_contact,
    posture,
    head_stability,
    question_results,
):

    doc = SimpleDocTemplate(
        "Interview_Report.pdf",
        rightMargin=40,
        leftMargin=40,
        topMargin=40,
        bottomMargin=40,
    )

    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        "CustomTitle",
        parent=styles["Title"],
        fontName="Helvetica-Bold",
        fontSize=28,
        textColor=colors.HexColor("#06B6D4"),
        alignment=TA_CENTER,
        spaceAfter=20,
    )

    subtitle_style = ParagraphStyle(
        "Subtitle",
        parent=styles["Heading2"],
        fontName="Helvetica-Bold",
        fontSize=18,
        textColor=colors.HexColor("#0F172A"),
        alignment=TA_CENTER,
        spaceAfter=30,
    )

    heading_style = ParagraphStyle(
        "Heading",
        parent=styles["Heading2"],
        fontName="Helvetica-Bold",
        fontSize=16,
        textColor=colors.HexColor("#0891B2"),
        spaceBefore=15,
        spaceAfter=15,
    )

    normal_style = styles["Normal"]

    content = []

    # =====================================================
    # COVER PAGE
    # =====================================================

    content.append(
        Paragraph(
            "AI Interview Readiness Analyzer",
            title_style,
        )
    )

    content.append(
        Paragraph(
            "Interview Performance Report",
            subtitle_style,
        )
    )

    content.append(Spacer(1, 0.6 * inch))

    current_date = datetime.now().strftime("%d %B %Y")

    cover_table = Table(
        [
            ["Interview Date", current_date],
            ["Assessment Type", "AI Mock Interview"],
            ["Generated By", "AI Interview Readiness Analyzer"],
        ],
        colWidths=[2.8 * inch, 3.2 * inch],
    )

    cover_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#0F172A")),
                ("TEXTCOLOR", (0, 0), (0, -1), colors.white),
                ("BACKGROUND", (1, 0), (1, -1), colors.whitesmoke),
                ("GRID", (0, 0), (-1, -1), 1, colors.grey),
                ("FONTNAME", (0, 0), (-1, -1), "Helvetica-Bold"),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
                ("TOPPADDING", (0, 0), (-1, -1), 10),
                ("ALIGN", (0, 0), (-1, -1), "CENTER"),
            ]
        )
    )

    content.append(cover_table)

    content.append(Spacer(1, 0.5 * inch))

    # =====================================================
    # EXECUTIVE SUMMARY
    # =====================================================

    content.append(
        Paragraph(
            "Executive Summary",
            heading_style,
        )
    )

    summary_data = [
        ["Metric", "Result"],
        ["Overall Readiness Score", f"{readiness_score:.2f}%"],
        ["Prediction", readiness_status],
    ]

    summary_table = Table(
        summary_data,
        colWidths=[3.5 * inch, 2.5 * inch],
    )

    summary_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#06B6D4")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("ALIGN", (0, 0), (-1, -1), "CENTER"),
                ("GRID", (0, 0), (-1, -1), 1, colors.grey),
                ("BACKGROUND", (0, 1), (-1, -1), colors.whitesmoke),
                ("BOTTOMPADDING", (0, 0), (-1, 0), 10),
            ]
        )
    )

    content.append(summary_table)

    content.append(Spacer(1, 0.4 * inch))

    # =====================================================
    # CAMERA ANALYSIS
    # =====================================================

    content.append(
        Paragraph(
            "Camera Behaviour Analysis",
            heading_style,
        )
    )

    camera_table = Table(
        [
            ["Metric", "Score"],
            ["Eye Contact", eye_contact],
            ["Posture", posture],
            ["Head Stability", head_stability],
        ],
        colWidths=[3.5 * inch, 2.5 * inch],
    )

    camera_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0F172A")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("GRID", (0, 0), (-1, -1), 1, colors.grey),
                ("BACKGROUND", (0, 1), (-1, -1), colors.beige),
                ("ALIGN", (0, 0), (-1, -1), "CENTER"),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("BOTTOMPADDING", (0, 0), (-1, 0), 10),
            ]
        )
    )

    content.append(camera_table)

    content.append(PageBreak())

    # =====================================================
    # QUESTION ANALYSIS
    # =====================================================

    # =====================================
    # QUESTIONS
    # =====================================

    content.append(
        Paragraph(
            "Interview Analysis",
            styles["Heading2"],
        )
    )

    for i, result in enumerate(question_results):
        content.append(
            Paragraph(
                f"<font color='#0891B2'><b>Question {i+1}</b></font>",
                heading_style,
            )
        )

        # ------------------------------------------
        # Question
        # ------------------------------------------

        question_table = Table(
            [
                ["Interview Question"],
                [result.get("question", "N/A")],
            ],
            colWidths=[6 * inch],
        )

        question_table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#06B6D4")),
                    ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                    ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                    ("BACKGROUND", (0, 1), (-1, -1), colors.whitesmoke),
                    ("GRID", (0, 0), (-1, -1), 1, colors.grey),
                    ("BOTTOMPADDING", (0, 0), (-1, 0), 10),
                    ("TOPPADDING", (0, 1), (-1, -1), 10),
                ]
            )
        )

        content.append(question_table)

        content.append(Spacer(1, 0.15 * inch))

        # ------------------------------------------
        # Transcript
        # ------------------------------------------

        transcript_table = Table(
            [
                ["Transcript"],
                [result.get("transcript", "Not Available")],
            ],
            colWidths=[6 * inch],
        )

        transcript_table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0F172A")),
                    ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                    ("BACKGROUND", (0, 1), (-1, -1), colors.beige),
                    ("GRID", (0, 0), (-1, -1), 1, colors.grey),
                    ("BOTTOMPADDING", (0, 0), (-1, 0), 10),
                    ("TOPPADDING", (0, 1), (-1, -1), 10),
                ]
            )
        )

        content.append(transcript_table)

        content.append(Spacer(1, 0.15 * inch))

        # ------------------------------------------
        # Scores
        # ------------------------------------------

        score_table = Table(
            [
                ["Metric", "Score"],
                [
                    "Fluency",
                    str(result.get("fluency_score", "-")),
                ],
                [
                    "Correctness",
                    str(result.get("correctness_score", "-")),
                ],
            ],
            colWidths=[3 * inch, 3 * inch],
        )

        score_table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#06B6D4")),
                    ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                    ("GRID", (0, 0), (-1, -1), 1, colors.grey),
                    ("BACKGROUND", (0, 1), (-1, -1), colors.whitesmoke),
                    ("ALIGN", (0, 0), (-1, -1), "CENTER"),
                    ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ]
            )
        )

        content.append(score_table)

        content.append(Spacer(1, 0.15 * inch))

        # ------------------------------------------
        # AI Feedback
        # ------------------------------------------

        feedback_table = Table(
            [
                ["AI Feedback"],
                [result.get("feedback", "No feedback generated.")],
            ],
            colWidths=[6 * inch],
        )

        feedback_table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0F172A")),
                    ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                    ("BACKGROUND", (0, 1), (-1, -1), colors.HexColor("#F8FAFC")),
                    ("GRID", (0, 0), (-1, -1), 1, colors.grey),
                    ("BOTTOMPADDING", (0, 1), (-1, -1), 10),
                    ("TOPPADDING", (0, 1), (-1, -1), 10),
                ]
            )
        )

        content.append(feedback_table)

        content.append(Spacer(1, 0.35 * inch))
        # =====================================================
    # AI RECOMMENDATIONS
    # =====================================================

    content.append(PageBreak())

    content.append(
        Paragraph(
            "AI Interview Summary",
            heading_style,
        )
    )

    if readiness_score >= 85:

        strengths = [
            "Excellent communication skills.",
            "Strong interview confidence.",
            "Very good body language.",
            "Technically well prepared.",
        ]

        weaknesses = ["Continue practicing advanced technical questions."]

    elif readiness_score >= 70:

        strengths = [
            "Good communication skills.",
            "Good technical understanding.",
            "Positive interview presence.",
        ]

        weaknesses = [
            "Improve confidence.",
            "Maintain more consistent eye contact.",
            "Practice answering with more structure.",
        ]

    elif readiness_score >= 50:

        strengths = [
            "Basic understanding of interview concepts.",
            "Shows potential with practice.",
        ]

        weaknesses = [
            "Improve communication fluency.",
            "Increase technical correctness.",
            "Maintain better posture.",
            "Improve confidence while answering.",
        ]

    else:

        strengths = [
            "Candidate attempted all interview questions.",
        ]

        weaknesses = [
            "Communication requires improvement.",
            "Technical knowledge needs strengthening.",
            "Body language should improve.",
            "Practice mock interviews regularly.",
        ]

    strengths_table = Table(
        [["Strengths"]] + [[f"✓ {item}"] for item in strengths],
        colWidths=[6 * inch],
    )

    strengths_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#10B981")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("GRID", (0, 0), (-1, -1), 1, colors.grey),
                ("BACKGROUND", (0, 1), (-1, -1), colors.HexColor("#ECFDF5")),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
            ]
        )
    )

    content.append(strengths_table)

    content.append(Spacer(1, 0.3 * inch))

    weaknesses_table = Table(
        [["Areas for Improvement"]] + [[f"• {item}"] for item in weaknesses],
        colWidths=[6 * inch],
    )

    weaknesses_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#EF4444")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("GRID", (0, 0), (-1, -1), 1, colors.grey),
                ("BACKGROUND", (0, 1), (-1, -1), colors.HexColor("#FEF2F2")),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
            ]
        )
    )

    content.append(weaknesses_table)

    content.append(Spacer(1, 0.4 * inch))

    verdict = f"""
    <b>Overall Verdict</b><br/><br/>

    Based on the complete interview assessment including speech analysis,
    camera behaviour analysis and the Machine Learning readiness prediction,
    the candidate achieved an overall readiness score of
    <b>{readiness_score:.2f}%</b>.

    Current Interview Status:

    <font color="#0891B2"><b>{readiness_status}</b></font>

    Continue practicing consistently to further improve technical knowledge,
    communication skills and interview confidence.
    """

    content.append(
        Paragraph(
            verdict,
            normal_style,
        )
    )

    content.append(Spacer(1, 0.6 * inch))

    footer = Paragraph(
        "<font size='9' color='grey'>Generated by AI Interview Readiness Analyzer • © 2026</font>",
        ParagraphStyle(
            "Footer",
            parent=normal_style,
            alignment=TA_CENTER,
        ),
    )

    content.append(footer)

    doc.build(content)

    return "Interview_Report.pdf"
